### ISSUE TITLE
Pin library using its group and name

### ISSUE THREAD

**Issue by FabienPennec** [littlerobots/version-catalog-update-plugin#104]
Hi, i need to pin specific libraries of a group in the format of group:name, as available with use-latest-versions plugin.
The libraries to pin are loaded from an external configuration and may not be present in the project.

The pin options allow pinning by groups, but not groups and names.

For example : 
```
  pin {
        // pins specific libraries by group and name
        libraries = ["my-group:my-lib-1", "my-group:my-lib-2", "another-group:another-lib"]
    }
```

**Comment by hvisser** [comment]
I don't really get what you are trying to do. Group + name is the full library coordinate. The term "pinning a group" is confusing because you are not just pinning the group, you are pinning specific libraries.

Pinning in the context of this plugin means "don't update the version automatically", so you'd just add these libraries to the toml file and then use that in the pinning configuration. Those libraries could also come from a different toml file.

Maybe your issue is that those libraries are not in a toml file and that you want to specify the coordinates as a string here?

**Comment by FabienPennec** [comment]
The plugin configuration is shared between many projects, with different libraries.
I want to have a global blacklist of specific libraries, directly defined in the configuration without modifying the toml file of the projects.

**Comment by hvisser** [comment]
You really have to give some more elaborate examples so that I can understand if this is just your specific use case, how it could be supported and if it makes sense for the plugin to support it. Thanks.

**Comment by hvisser** [comment]
What you can also consider is just to reject all updates for the plugins/libraries that you don't want to update by configuring the dependency versions plugin. This will probably give you the most options in terms of flexibility as that is intended to be scripted.
