### ISSUE TITLE
Keep publishing catalog module

### ISSUE THREAD

**Issue by Fs02** [littlerobots/version-catalog-update-plugin#121]
I think the catalog module is useful as standalone utility library too
https://mvnrepository.com/artifact/nl.littlerobots.vcu/catalog

**Comment by hvisser** [comment]
Sorry, but I don't have plans to do that. The library is pretty specific for the plugin and for publishing on the Gradle Plugin portal a single artifact was needed if I remember correctly. Since I want to publish the same artifact for the plugin on Maven and the Gradle Plugin portal there's no need anymore to publish the catalog module separately. The project structure will stay the same you you can always use it as source if needed.
