### ISSUE TITLE
Ignore Pinned Versions

### ISSUE THREAD

**Issue by jdelga** [littlerobots/version-catalog-update-plugin#124]
I am using this plugin with several pinned versions in my toml file which usually require a manual update as they need to be compatible with other libraries, such as AGP with other plugins.

I wonder if it is possible to enable an option to ignore all configurations in `pinned` and `keep` libraries, so that I am aware that a new version is available.

Thank you very much!

**Comment by hvisser** [comment]
The plugin should tell you that there's a new version already. Also if you run with `--interactive` the pinned items are commented out but the version is updated so that you can decide if you want to update them anyway.

The only caveat here (mostly for things you `keep`) is that the dependency needs to be actually used in your project as a dependency, otherwise the versions plugin will not detect any new versions for it.

**Comment by hvisser** [comment]
I think the plugin already does what you want, and I'd need more info if it doesn't, so closing for now.
