### ISSUE TITLE
Gradle task not generated

### ISSUE THREAD

**Issue by SkyleKayma** [littlerobots/version-catalog-update-plugin#14]
Hi,

Probably doing something wrong but can't figure out what.
The task `versionCatalogUpdate` is never generated.

The task `dependencyUpdates` from `https://github.com/ben-manes/gradle-versions-plugin` is well generated.

I declared this as below:
```
dependencies {
    ...
    classpath(libs.pluginGradle.versions.catalog)
}
```

Where in toml file there is : 
```
[versions]
versions-catalog-gradle-plugin = "0.2.1"

[libraries]
pluginGradle-versions-catalog = { module = "nl.littlerobots.vcu:plugin", version.ref = "versions-catalog-gradle-plugin" }

```

This is not generating the task. And adding this line is not helping cause I get the error below:
```
plugins {
    id("com.android.application")
    ...
    id("nl.littlerobots.version-catalog-update")
}
```

Error:
`Caused by: java.lang.IllegalStateException: Should be applied to the root project only`

Any idea ?
Thx for your time ! 👍

**Comment by SkyleKayma** [comment]
I figured out what I've done wrong, For whose asking the same, add this on top of root build.gradle file (here .kts):

```
apply(plugin = "com.github.ben-manes.versions")
apply(plugin = "nl.littlerobots.version-catalog-update")
```

I'm closing it.

**Comment by hvisser** [comment]
Correct, `Caused by: java.lang.IllegalStateException: Should be applied to the root project only` means that you should apply this to the root project, not your app project.

For declaring the plugin when you add it to your toml file, it's easiest to use the `plugin` section:

```
[plugins]
versionCatalogUpdate = "nl.littlerobots.version-catalog-update:0.2.1"
```

Then reference it in your _root_ build.gradle.kts using an plugin alias:

```
plugins {
    alias(libs.plugins.versionsBenManes)
    alias(libs.plugins.versionCatalogUpdate)
}
```

You can check out a working project here https://github.com/code-with-the-italians/bundel

In your example you are mixing syntax for adding plugins, if you use `plugin` then you don't need `classpath` for the build script dependencies. If you use `classpath` then you should use `apply` to apply the plugin to your root build script.
