### ISSUE TITLE
Let configure the new key format for TOML file

### ISSUE THREAD

**Issue by konikvranik** [littlerobots/version-catalog-update-plugin#15]
Hello, thank you for very useful plugin.

It will be nice to be capable to configure the format of the newly added key for the TOML file. Currently you just replace dots for hyphens, but it will be nice to be capable to use camelCase keys too.
Maybe accepting configuration closure which will do the transformation, so users can customise it their needs.

**Comment by hvisser** [comment]
Thanks for the suggestion, I guess this is mainly important for creating the initial catalog, after there is a `libs.versions.toml` file the only new identifiers that are added could be for a version. I'm wondering if adding a setting for that is worth it as it's easy to change manually. 

For creation one other option would be just to add a camel case command line option or something, though I think that even when you camel case the keys, you'd always want to edit them anyway. Because module ids can be anything it's not straightforward to create a suitable key.

**Comment by konikvranik** [comment]
I meant it more for automatic updated of jte dependencies with adding allowed.
I agree, that it is not so complicased to rename the key manually then because add usecase is not so often.
But it would be nice to have it without additional renaming. Just as a cherry on the top ;-)
And relaying it on the user looks like easy and versatile option. The default will be current algorithm just replacing the dots.

**Comment by hvisser** [comment]
I'm closing this for now, since there's always going to be some editing needed when creating a catalog file + since this is basically a one time action, I feel that adding more options to configure these initial keys would be a bit overkill.
