### ISSUE TITLE
Docs or feature to remove final -> alpha updates

### ISSUE THREAD

**Issue by yschimke** [littlerobots/version-catalog-update-plugin#25]
~I think this works~

This doesn't work but is close to what I'd like to achieve.

```
configurations {
    metadataRulesConfig {
        resolutionStrategy {
            componentSelection {
                all { ComponentSelection selection ->
                    if (selection.candidate.version.contains("alpha")) {
                        selection.reject("don't use alpha candidates")
                    }
                }
            }
        }
    }
}
```

It won't prompt to update to alpha, but unfortunately doesn't update existing Alphas either.  This is particularly relevant for Jetpack, where an Alpha might be needed for glance, but the rest of dependencies should follow the latest final.

**Comment by hvisser** [comment]
There are multiple ways to configure this, and I'd personally would opt for configuring [the versions plugin](https://github.com/ben-manes/gradle-versions-plugin#rejectversionsif-and-componentselection) and not the the resolution strategy applied to the entire project. 

There's also an example of preventing to switch "channels" for a dependency, e.g. if you have an alpha applied you can upgrade to another alpha, but if you are currently on a "stable" version that alpha upgrade is not allowed.

Your example of configuring a resolution strategy can also be valid, but it would be enforced on the entire project, not just in the context of updating the versions. It could be what you want, or it could not be :)

Wherever you configure this, filtering on juist "alpha" or any version prefix/postfix is tricky because a version can be _anything_ really.

The README is already pointing to the versions plugin documentation as it builds upon it. I'm a bit hesitant trying to document all the various ways of how you can filter on dependencies with the versions plugin because of all of the above, so I think for now pointing to the version plugin docs would be what I'd prefer.
