### ISSUE TITLE
Is multi project setup supported?

### ISSUE THREAD

**Issue by rvplauborg** [littlerobots/version-catalog-update-plugin#34]
Hi,

I am using a multi project setup using `buildSrc` and convention plugins as described at https://docs.gradle.org/current/samples/sample_convention_plugins.html. So I do not have a single "root" `build.gradle.kts`. Is there support for my setup currently? I tried applying the plugin in my `buildSrc/build.gradle.kts` but that does not work.

**Comment by hvisser** [comment]
This is more of a Gradle question I suppose, but even if you have conventions plugins to configure your modules, you should probably still have a root `build.gradle` where this and the versions plugin should be applied. If you don't have a root `build.gradle` then you could either create one or configure the plugin in your convention plugin on the root project, but I'd probably just configure it using a build file since it applies to the entire project. 

Applying the plugin to your `buildSrc` Gradle file doesn't work because that is basically a separate project that only exists to compile your convention plugin.

What's important here is that the [versions plugin](https://github.com/ben-manes/gradle-versions-plugin) can evaluate all of the dependencies in the entire project, regardless from what you are doing through `buildSrc`.

**Comment by rvplauborg** [comment]
Thank you for the elaborate answer!

**Comment by GavinRay97** [comment]
@hvisser Could I ask what you mean by `configure the plugin in your convention plugin on the root project`?

I also followed the Gradle suggestion to use `buildSrc` and create "conventions", so my application looks like this:
```
settings.gradle.kts

/buildSrc
  build.gradle.kts
  /src/main/kotlin
    kotlin-library-conventions.gradle.kts

/app
  build.gradle.kts

/util-library-1
  build.gradle.kts
```

**Comment by hvisser** [comment]
I think the recommendation is to use included builds and not buildsrc...in both cases you should consider the included builds as separate projects I think, and I was suggesting to apply the versions plugin and the version catalog plugin to the root build files of your included builds. I haven't tested this though. If you have an example project I'm happy to take a look.

**Comment by GavinRay97** [comment]
@hvisser I actually managed to figure it out, thanks for getting back to me! 

For anyone else who runs into this question from Google, the following worked for me:

- Create a root `build.gradle.kts` in the root of the repo
- Add the dependencies there:

```kts
plugins {
    id("com.github.ben-manes.versions") version "0.44.0"
    id("nl.littlerobots.version-catalog-update") version "0.7.0"
    id("com.autonomousapps.dependency-analysis") version "1.17.0"
}
```

Now running the `version catalog` tasks will apply to all sub-projects automatically, and generate a unified report 🎉
