### ISSUE TITLE
How to update to the stable version?

### ISSUE THREAD

**Issue by anticafe** [littlerobots/version-catalog-update-plugin#43]
I notice the plain report also list some unstable version (alpha, RC).
For example:
```
The following dependencies have later milestone versions:
 - androidx.appcompat:appcompat [1.3.1 -> 1.6.0-alpha04]
     https://developer.android.com/jetpack/androidx/releases/appcompat#1.6.0-alpha04
 - androidx.appcompat:appcompat [1.4.0 -> 1.6.0-alpha04]
     https://developer.android.com/jetpack/androidx/releases/appcompat#1.6.0-alpha04
 - androidx.lifecycle:lifecycle-viewmodel-savedstate [2.4.0 -> 2.5.0-rc01]
     https://developer.android.com/jetpack/androidx/releases/lifecycle#2.5.0-rc01
 - androidx.browser:browser [1.3.0 -> 1.4.0]
     https://developer.android.com/jetpack/androidx/releases/browser#1.4.0
```
How can I force this plugin to only check for update these stable version instead?

**Update:**
I notice there is a [sample code snippet](https://github.com/matiascalvo/compose-kotlin-repositories/blob/main/buildscripts/toml-updater-config.gradle) to only accept the stable version. Do you think can integrate it to your plugin?

**Comment by hvisser** [comment]
The selection of acceptable versions is controlled by the [versions plugin](https://github.com/ben-manes/gradle-versions-plugin#rejectversionsif-and-componentselection). The snippet you referenced is an example of such configuration.

It's a bit tricky to set this as a default from this plugin because I don't think there's a good way to detect if config is set on the versions plugin. Because it might depend on what are acceptable versions in a project (and versions could have all kinds of formatting), it's also tricky to have a good default set of configuration. A "stable" version could mean different things to different projects. Some projects might find a release candidate acceptable, others might not for example.

That said, maybe it would make sense to have some option to set defaults. The only question would be how those would be applied and which defaults would make the most sense.

**Comment by anticafe** [comment]
Thanks @hvisser for quick reply. 
I think the selection of acceptable version is an advanced configuration. So, it would be useful enough if you provide the a configuration (for example `nonStableVersionPostfixes = ["-alpha", "-rc"]`), then it's up to developer to tweak it.

**Comment by hvisser** [comment]
This is actually linked in the README, but I suppose it can expanded a bit, added #45 for this.
