### ISSUE TITLE
Create option still looks for latest versions first

### ISSUE THREAD

**Issue by SidB3** [littlerobots/version-catalog-update-plugin#47]
On running `gradle versionCatalogUpdate --create` the plugin is looking through my repositories for latest versions.

My understanding is that per #13 `--create` option will create a toml file with current versions only, so doing a update check seems redundant?

**Comment by hvisser** [comment]
I think the check you are seeing is the dependency versions plugin, which always serves as input for generating or updating the toml file. Running that plugin reports both current and available versions, and for `--create` the current entries are used. 

So I think what you are seeing is expected, unless the versions in your toml file are actually updated when you do a `--create`.

**Comment by SidB3** [comment]
Understood, I looked through the documentation 0f `gradle-versions-plugin` to see if there is a flag that tells it to simply report current versions instead of doing an update check but there is none.

I am hoping to use your plugin to get started on creating a toml file for version catalog integration in my project. It has hundreds of dependencies and we don't normally automate dependency updates.

We can close the issue, I guess I just need to wait for the plugin to compete the update checks.

**Comment by hvisser** [comment]
If the speed of the versions plugin is a problem then you could try [this suggestion](https://github.com/littlerobots/version-catalog-update-plugin/issues/2#issuecomment-959961439). 

Creating the catalog on an existing project using hundreds of dependencies will always be a bit painful, since you'll want to rename the entries and you'd still need to update the actual dependency references. After that, it should be much better, especially if you run the plugin on regular basis and pick and choose what you want to update.
