### ISSUE TITLE
Allow configuring dependency / plugin output format

### ISSUE THREAD

**Issue by Nek-12** [littlerobots/version-catalog-update-plugin#60]
I'd like to keep my toml file tidy and follow a single standard for how deps are defined. 
However, running `versionCatalogUpdate --create` produces the following:
```
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detektFormattingPlugin" } // added by me
io-github-hoc081098-FlowExt-jvm = "io.github.hoc081098:FlowExt-jvm:0.3.0"
io-insert-koin-koin-core = { module = "io.insert-koin:koin-core", version.ref = "io-insert-koin" }
```
The problem above is the inconsistency of specifying a hardcoded version and creating a version reference and the format that uses module/group+name (I prefer second)

Is there a way to force the script to create version refs for all dependencies?
Is there a way to specify whether I want the script to use the `group+name`  or `module` declaration styles?

**Comment by hvisser** [comment]
Create will only create `version.ref` and `versions` if there are multiple group ids sharing that version. It will not do this for libraries where this is not the case. Otherwise you'd end up with a bunch of more or less useless versions IMHO. The plugin will prefer the shortest notation possible for a library or plugin.

If you manually declare a `version.ref` however, it will retain the version you declared. While that might be some work, there will always be clean up work when using `--create`, and that will be a one time thing to do. 

I don't intent to add customisations for formatting, the goal is to be a bit opinionated so that we don't have to discuss what looks pretty to some or useless versions to others :)
